stages:
  - build-dependencies
  - tests
  - publish

lint:8.0:
  dependencies: []
  stage: build-dependencies
  image: php:8.0
  script:
    - find . -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
  tags:
    - docker
    - dind

Composer dependencies:
  stage: build-dependencies
  dependencies: []
  image: registry.mehrkanal.com/docker/phpx/cli:8.0-build
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - composer install --prefer-dist
  artifacts:
    expire_in: 3 days
    paths:
      - vendor/
  cache:
    paths:
      - vendor/

Code Style Checks:
  dependencies: ["Composer dependencies"]
  stage: tests
  image: registry.mehrkanal.com/docker/phpx/cli:8.0-build
  script:
    - composer run ecs
  tags:
    - docker
    - dind

Publish Composer package:
  stage: publish
  variables:
    packagename: git@gitlab.mehrkanal.com:$CI_PROJECT_PATH.git
  trigger:
    project: mehrkanal/packageserver
    branch: master
    strategy: depend

  rules:
    - if: '$CI_COMMIT_TAG'
    - when: never
