include:
  - project: 'candy-shop/gitlab-ci-templates'
    ref: master
    file:
     - '/templates/.metrics.yml'
     - '/templates/.composer.yml'
     - '/templates/.phpstan.yml'
     - '/templates/.ecs.yml'
     - '/templates/.php-lint.yml'
     - '/templates/.update-packageserver.yml'

variables:
  PHP_VERSION: "8.1"

stages:
  - precheck
  - dependencies
  - analyze
  - publish
